# Generated by Django 5.2.17 on 2026-09-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_content_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='states',
            new_name='status',
        ),
    ]
